remote_theme: airspace-jekyll

title: Predicting Player Performance in PUBG
description: Final project for 140.711 Advanced Data Science (Fall 2018)

show_downloads: true

navbar-links:
  Overview: "https://pubg-prediction/project"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"
