exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Predicting Player Performance in PUBG
subtitle: "Final project for 140.711 Advanced Data Science (Fall 2018)"
url: "http://pubg-prediction.github.io"
baseurl: "/project"
cover: "/img/slider-bg.jpg"

# Build settings
markdown: kramdown
